### ISSUE TITLE
Error visualization in appendix

### ISSUE THREAD

**Issue by giwel** [fdarmon/NeuralWarp#10]
Dear @fdarmon 

Thank you very much for your work. In your error visualization in appendix, the GT points look very clean compared to the provided GT. I wonder if you preprocess the GT points from DTU to get such visualization.

Look forward to your reply!

**Comment by fdarmon** [comment]
Hi sorry for the late reply. 

Yes I cleaned the point cloud similar to what is done in DTU visualization code. I removed every point with an error above 20.

**Comment by giwel** [comment]
Thank you!
