### ISSUE TITLE
result visualization

### ISSUE THREAD

**Issue by decai-chen** [fdarmon/NeuralWarp#11]
Hello,

thanks for your excellent work! I am wondering how you create the result visulization teaser.gif in readme, with a moving camera and a sliding bar to switch between two meshes. Thank you in advance!

Best regards

**Comment by fdarmon** [comment]
Hello, 

Thanks for your interest in our work. Unfortunately I do not have access to the code I used for the video but I implemented most of it myself: I generated renderings of the mesh using a circle trajectory, then I manually combined each pairs of image using simple black bar between the two and then pack the full sequence in a gif. Apart for the rendering I did not use any library to generate the sliding bar or the moving camera. 

Hope this helps

**Comment by decai-chen** [comment]
Hello, 
thanks for your answer!
Best regards
