### ISSUE TITLE
The result on DTU scan24 does not align to the paper

### ISSUE THREAD

**Issue by SAOHPRWHG** [fdarmon/NeuralWarp#14]
Follow the instruction of this repo. I got a result, 0.72, on DTU scan24 scene, which is different from the result in this paper, 0.49.
Could you please tell me if anywhere I made some mistakes?
![image](https://user-images.githubusercontent.com/43441551/200168086-61b91e92-1441-49fb-bc61-251b74b82495.png)

**Comment by SAOHPRWHG** [comment]
These are my training and extracting commands:
python train.py --conf confs/NeuralWarp.conf --scene 24
python extract_mesh.py --conf confs/NeuralWarp.conf --scene 24

**Comment by fdarmon** [comment]
It looks like you have not trained the baseline model before finetuning? 

First run `python train.py --conf confs/baseline.conf --scene 24` then `python train.py --conf confs/NeuralWarp.conf --scene 24`

**Comment by SAOHPRWHG** [comment]
Thanks! I got the correct result.
