### ISSUE TITLE
Is Patch Warping enabled in current Codebase ?

### ISSUE THREAD

**Issue by anuveshkumaratavataar** [fdarmon/NeuralWarp#2]
Hi, Thanks for the excellent paper. 

I was going through the code base and the warping seems to happen only for random pixels sampled on the image plane (viz. clipped off at boundaries), and not patches. 
line 155-166 in https://github.com/fdarmon/NeuralWarp/blob/main/datasets/scene_dataset.py

Is it right, or am I missing something ?

**Comment by fdarmon** [comment]
Hi, thanks for the question. 

In the lines of code you mention, we indeed pick random pixels in the image (cliped off at boundaries). But we use the patch located around these pixels, see in the loss computation for example https://github.com/fdarmon/NeuralWarp/blob/main/training/loss.py#L90

I hope this helps,
François
