### ISSUE TITLE
How to reduce the GPU memory usage

### ISSUE THREAD

**Issue by BianFeiHu** [fdarmon/NeuralWarp#6]
Hello, I encountered OOM Error after "generate_visu" on RTX3080, can you provide some suggestions on how to reduce batch size or use multiple GPU?
![image](https://user-images.githubusercontent.com/57490712/177325379-b7b28320-55d4-4f40-9974-79fb39bc1dfa.png)

**Comment by fdarmon** [comment]
Hello, 

I have not implemented a multi-gpu version yet. You can decrease the number of rays to optimize from 512 to 400 with `train/num_pixels=400` in `NeuralWarp.conf`. It should solve the OOM problem but the results may not look the same.
